#!/usr/bin/env python2.6

# given a config and a list of LHE files, make copies of the config
# for each LHE input file, prepending the given prefix
import os
import sys
import pwd
import os.path

from optparse import OptionParser
from CMSYAAT.FileCache.ConfigCache import ConfigCache
import FWCore.ParameterSet.Config as cms

# TODO: Get some common options parsing
parser = OptionParser()
parser.add_option("-f", "--filename", dest="filename",
                  help="Configuration to dump")

parser.add_option("--prefix", dest="prefix",
                  default="root://xrootd.unl.edu//store/user/%s/LHE/" % \
                                pwd.getpwuid(os.getuid())[0],
                  help="Prefix to add before the filename. " +\
                       "Note: use 'root://xrootd.unl.edu//store/user/SOME/PATH'"+\
                       " to load from xrootd (strongly recommended). This works"+\
                       " for all US-based Tier2s. Place the LHE files on your "+\
                       "SE and it will be globally accessible")

parser.add_option("-u", "--user", dest="user",
                  help="Username to store as", default=pwd.getpwuid(os.getuid()))
parser.add_option("-g", "--group", dest="group",
                  help="Group to store as", default="CMSYAAT")
parser.add_option("--hostname", dest="hostname",
                  help="Target couch instance (formatted as http://andrewmelo.cloudant.com:5984)",
                  default="http://se2.accre.vanderbilt.edu:5985")
parser.add_option("-d", "--database", dest="database",
                  help="Target database", default="wmagent_configcache")

(options, args) = parser.parse_args()

# Load the config initially (takes forever)
cacheFile = ConfigCache()
config = cacheFile.loadConfig( options.filename )
for filename in args:
    # Modify the config for this filename
    targetName = "%s%s" % ( options.prefix, os.path.basename( filename ) )
    config.process.source = cms.Source("LHESource",
        fileNames = cms.untracked.vstring(targetName)
    )

    # Upload the config to the cache
    target = cacheFile.upload(config, options.user, options.group,
                    url=options.hostname,
                    database=options.database,
                #    arguments=args,
                    label = os.path.basename(filename),
                    description = "LHE for SusyScan. Generated by Andrew Melo",
                    )
    print "Uploaded %s to %s" % ( os.path.basename(filename), target )
